### ISSUE TITLE
Enum type

### ISSUE THREAD

**Issue by roitman-g** [koskimas/kysely#112]
I wonder if it is possible to create enum types with Kysely? I have not found anything in docs

**Comment by koskimas** [comment]
Well, you can create anything with raw SQL using the `sql` template tag. You can run raw sql in migrations. On the typescript side enums work just fine. Just create an enum and use if for a field.

No enum support has been added to the schema builder because all database engines have different implementation for enums. Also people mean different things when they talk about enums. On postgres there's a way to create new enum types and use those as columns. AFAIK no other engine has something like that. Even knex simply creates a check constraint for enums by default, even on postgres.

Kysely doesn't have an abstraction layer on top of SQL. Therefore there's never going to be a `.addColumn('foo', 'text', col => col.enum(['a', 'b', 'c'])` kind of methods.

There are already methods for creating check constraints, but you still need to write the check code using raw sql.

What kind of support would you like see in kysely? And what do YOU mean by enum types?

**Comment by koskimas** [comment]
@roitman-g Any thoughts?

**Comment by koskimas** [comment]
Did you go mute?

**Comment by vladstavarache** [comment]
For postgres you can do:

`await db.schema
    .createType("status")
    .asEnum(["failed", "success"])
    .execute();`

and then reference the status type:

`.addColumn("status", "status")`

**Comment by bhgames** [comment]
When I do this, it throws a ts error saying that is not assignable to DataTypeExpression

**Comment by igalklebanov** [comment]
@vladstavarache fixed your example with sql template tag usage in `.addColumn`.

@bhgames check the example again.

**Comment by leleofg** [comment]
the example above worked for me! I'm using postgres
thanks @vladstavarache

**Comment by anoopsimelabs** [comment]
> @vladstavarache fixed your example with sql template tag usage in `.addColumn`.
> 
> @bhgames check the example again.

@igalklebanov ,  For me the following solution worked, when I want to use different name(**UserStatus**) for type. 

```
await db.schema
    .createType("UserStatus")
    .asEnum(["failed", "success"])
    .execute();
```
and then reference the **UserStatus** type:
```
.addColumn("status", sql`"UserStatus"`)
```

**Comment by 0xPT** [comment]
@anoopsimelabs @vladshcherbin  how would you do migrations if you need to change the type? It doesn't seem like db.schema has any way to change the type. Is it better to just do raw SQL for this?
