### ISSUE TITLE
Discord invite in the README is invalid

### ISSUE THREAD

**Issue by thelinuxlich** [koskimas/kysely#154]
It expired some time ago.

**Comment by koskimas** [comment]
Nope it hasn't. The link never expires. There's some bug in discord that randomly says that for random people.

**Comment by thelinuxlich** [comment]
Maybe some permission issue?

**Comment by koskimas** [comment]
![Screenshot_20220906-172602](https://user-images.githubusercontent.com/846508/188661280-e817fd09-6b53-4f7a-8597-fb169477d07a.jpg)

There are no permissions to change. The link works when I tried it (in incognito mode obviously)

**Comment by koskimas** [comment]
You can use this one for now. It expires in a week.

https://discord.gg/mbAhhE4b

**Comment by igalklebanov** [comment]
Tested with another discord user of mine, and it worked. closing this issue.

**Comment by waynebloss** [comment]
@koskimas The Discord invite is not working today. It says "Invite Invalid" and that the link may have expired.

I don't understand why you won't just enable the Discussions setting here on Github though... It would be so much simpler and better since everyone is already logged into GitHub and when you search on Google, you can actually find things in GitHub discussions.

Discord is essentially useless and it might as well not even exist for the intended usage.

**Comment by steviec** [comment]
FWIW I can't get on the Discord either.

**Comment by koskimas** [comment]
Anyone having trouble joining discord, try copy-pasting the link from the badge and navigating to that directly. The link IS valid. There's some weird bug in either discord or using it through the badge.

@waynebloss I think I explained this to you in your issue. Or are you unable to understand everything/everyone that disagrees with you?

**Comment by koskimas** [comment]
@waynebloss I already answered you in the issue, but here it is for other people: We have issues for feature requests/discussions and discord for other discussions/help. There is a search in discord and later we can add more channels. It would be confusing to have yet another place for discussions. Discord is widely used for this purpose and many people prefer it.

Also since you seem to be somewhat pissed, try to remember that I'm the person that's answering all your questions currently. What you are essentially demanding is that I actively follow yet another place. I'm not getting paid. I'm doing this on my free time.

**Comment by waynebloss** [comment]
@koskimas I'm sorry, but you did not answer any my main concern in the previous issue. Also, I am not "pissed" at all, I'm simply providing argumentation for what I believe is the correct course of action. If there's something specific that you think was rude or angry, could you please point that out for me so I can correct this behavior?

(Or, can anyone else help me with this based on the discussion here and #155 ?)

I see no evidence that it would be confusing to have another place with discussions. It's actually more confusing to have a discussion channel that people can't access for unknown reasons as we've seen here and that search engines cannot index.

> I'm the person that's answering all your questions currently.

The point of a very easily accessible discussion channel is to avoid having you answer any of the questions and to let others discuss among themselves freely and easily.

**Comment by koskimas** [comment]
Thank you! You have a good day too!
