### ISSUE TITLE
Misleading type errors I found

### ISSUE THREAD

**Issue by thelinuxlich** [koskimas/kysely#195]
I discovered recently that sending an object instead of an array of objects to `.values()` will make Kysely "lie" about what's wrong. In this screenshot, the `created` field is wrong(should be Date instead of string) but the error complains about the first field being invalid: 
![image](https://user-images.githubusercontent.com/5043/195706265-8939ae18-87ae-4ace-86ea-1f613390f2a3.png)

For reference, the error when using an array of objects, still doesn't show which field is wrong but at least doesn't complain about a valid field: 
![image](https://user-images.githubusercontent.com/5043/195706843-c06a3276-8e87-426f-b734-f82c99a24239.png)

Another strange error output when using `.having()`, in this screenshot the RHS is `number | null` so it will fail but the message is very cryptic:
![image](https://user-images.githubusercontent.com/5043/195707292-1a862b2d-1888-4344-bab9-aefe2fc9ed51.png)

**Comment by igalklebanov** [comment]
Sadly we only have control of when typescript compiler yells at you, but not on the contents of its yells.

To my understanding..

First incident: 
Function signature has 2 overloads, one for single `InsertObject`, the other for an array of `InsertObject`s. TS Compiler tries matching your object to both overloads and fails in doing so, but is not sure about your intentions, so it yells about both mismatches. 
First overload error should be the one to worry about -- you passed an object that doesn't match the expected interface, second one is irrelevant -- you provided keys that do not exist in js arrays.

Second incident:
`.having(lhs, op, rhs)` compares apples to apples. `parcelas` is of type `number | null`, `count(...)` returns `string | number | bigint` by default - there's your mismatch. 
The error is that way because none of the `ValueExpression` types (that expect a nullable value type because of lhs) matched to the `RawBuilder<number | null>` argument you passed, so it used `AnySelectQueryBuilder` as a fallback -- is not same class so it yells about privates and stuff.
