### ISSUE TITLE
Migrations failed on windows with ESM

### ISSUE THREAD

**Issue by kokororin** [koskimas/kysely#254]
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:

On windows, we need to write file:///c:/x/y/z instead of c:/x/y/z

https://github.com/nodejs/node/issues/31710

**Comment by koskimas** [comment]
You pass in the migration folder yourself. Use a relative path instead of absolute?

**Comment by kokororin** [comment]
pass migration folder starts with `file:///` not fixed it, must use relative path.

**Comment by drewbitt** [comment]
Yes paths must be relative with ESM

e.g. 

```js
path.relative(".", path.join(__dirname, 'migrations'))
```

**Comment by douglasg14b** [comment]
This kind of means migrations are  a noop.

Absolute path doesn't work OOTB because of the way Kysley imports it.

Relative path doesn't work OOTB because `ERR_INVALID_MODULE_SPECIFIER`

**Comment by igalklebanov** [comment]
Give `kysely-ctl` a try. If you need programmatic badly, it exposes its own file migrator implementation (`TSFileMigrationProvider`).

**Comment by escalonn** [comment]
this issue is not resolved; https://github.com/kysely-org/kysely/issues/254#issuecomment-3235310304 is correct. there is nothing you can pass to `FileMigrationProvider()` that will let it work on Windows in ESM, unless you use holzmaster's silly hack above, like i am also forced to do. relative paths throw `ERR_INVALID_MODULE_SPECIFIER`. absolute paths throw `ERR_UNSUPPORTED_ESM_URL_SCHEME`.
the import code in `file-migration-provider.ts` is simply incorrect for this platform.
