### ISSUE TITLE
Prefix non query building methods

### ISSUE THREAD

**Issue by koskimas** [koskimas/kysely#260]
The query builders and other objects have methods that map more or less directly to SQL concepts. These methods build the SQL.

In addition to those, there are also other methods that don't contribute to the SQL like `if`, `withPlugin`, `assertType`, `call` etc.

Finally each class has a small set of methods related to compiling and executing the sql like `compile()`, `execute()`, `executeTakeFirst()` etc.

@thelinuxlich and @igalklebanov had a great idea of prefixing the non-sql methods with `$`.

The question remains, should we also prefix the compilation/execution methods? My initial feeling is to not prefix `compile()`, `execute()` etc. as they are fundamentally related to SQL since the queries need to be executed or at least compiled to be useful.

What do you think?

**Comment by igalklebanov** [comment]
I think `.execute()` (and variants) & `.compile()` are fine because they're used at the end of the chain. 

Our readability issues are with utility non-sql methods that are called "inside" the chain, in between methods that actually map to sql clauses and keywords.

Prefixing these non-sql methods will also help with their discoverability, just open intellisense in your IDE and type `$` to get a list of all the utility stuff.

**Comment by koskimas** [comment]
When implemented, let's leave the old methods with a deprecation warning. Something like

```ts
/**
 * @deprecated Use $call instead.
 */
call<T>(func: (qb: this) => T): T {
  return this.$call(func)
}
```
