### ISSUE TITLE
Referentially transparent API

### ISSUE THREAD

**Issue by steida** [koskimas/kysely#30]
> An expression is called referentially transparent if it can be replaced with its corresponding value (and vice-versa) without changing the program's behavior.

It would simplify Kysely usage and unlock further optimizations. And it's little change I believe.
Take a look how I'm using Kysely in React:

```ts
const { data, refresh } = useThingsDB(
  useCallback((db) => db.selectFrom('thing').selectAll().execute(), []),
);
```

`useThingsDB` is React Hook (composed from other hooks but that's irrelevant now), which takes Kysely query as a parameter. Note `useCallback` usage. It makes callback stable because it must be stable.

What am I proposing is toString overload that would serialize Kysely toString and fromString that would deserialize it. With such API, it would be easy to cache etc. Kysely queries.

```ts
const { data, refresh } = useThingsDB((db) =>
  db.selectFrom('thing').selectAll(),
);
```

What do you think?

**Comment by koskimas** [comment]
So you want to be able to serialize queries, not the whole `Kysely` instance with drivers, connections, plugins and all?

So something like this:

```ts
const serialized: string = db.selectFrom('thing').selectAll().serialize()
const query = db.deserialize(serialized)
```

That should be doable, but the type of `db.deserialize(serialized)` would obviously be wrong, since we can't deserialize the type from just a `string`. The deserialized query would be something like `QueryBuilder<DB, any, unknown>`.

I don't think we should override `toString()`. People would assume `toString()` returns the SQL and `fromString` parses SQL into a QueryBuilder.

You can already serialize the query like this:

```ts
const serialized = JSON.stringify(query.toOperationNode())
```

**Comment by steida** [comment]
Yes, only the query.

Agreed, toString is too invasive. JSON is better, yes.

toOperation node is probably good enough, maybe we don't need deserialization at all. Will check it.

Thank you for the answer.

**Comment by steida** [comment]
@koskimas Is there an interface representing a valid SQL? To detect:

`db.selectFrom('thing')` not valid
`db.selectFrom('thing').selectAll()` valid, toOperationNode can be called.

**Comment by steida** [comment]
Hmm, forget about it. It's specialized keys. I don't want to distract you.
