### ISSUE TITLE
Feature request - result of migration run

### ISSUE THREAD

**Issue by midwesterntechnology** [koskimas/kysely#41]
Would it be possible for the migration function to return some information about the migrations performed? Even just a count of migrations executed would be helpful (we use this to automatically drop and recreate some views that are auto-generated based on the schema - but we dont want to do this if the schema hasn't changed).

**Comment by koskimas** [comment]
Sure! I can make them return a list of objects with a migration name and a status (success, error, notExecuted). ` notExecuted` would be for migrations that should have been executed but weren't because an earlier migration failed.

**Comment by koskimas** [comment]
This is now implemented in 0.13.0.

**Comment by steida** [comment]
> never throw but return this object instead.

Awesome. It's almost always better to return `Either` or `These` instead of throwing errors.

If I understand it correctly, MigrationResultSet can succeed, fail, or something between. That's `These`.  https://github.com/gcanti/fp-ts/blob/master/src/These.ts

Modeling it as l algebraic data type would improve DX I suppose. 

`Either` is Left or Right (fail or success), `These` is Left or Right or Both.
