### ISSUE TITLE
A few ideas and thank you

### ISSUE THREAD

**Issue by xiaoyu-tamu** [koskimas/kysely#5]
Hi there, I have been trying this lib this weekend. By far, this is the most powerful and lightweight type-safe sql query builder IMO. (compares to knex, zapatos and slonik) 

I'm using `prisma2` in production but would love to migrate some of the queries to kysely once it become stable.

I love the amazing work you have done and I think this work could be improved if it could support stricter type.

Assuming i have the following DDL

```sql
CREATE TABLE person
(
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY
    CONSTRAINT person_pk
      PRIMARY KEY,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW()            NOT NULL
  name                text                                              NOT NULL
)
```

I would expect the following code throw because name non-nullable

```ts
interface Person {
  id: number
  created_at: string
  name: string
}

interface Database {
  person: Person
}

const db = new Kysely<Database>

await db.insertInto('person').values({})
```

The current behavior typescript does not raise exception because the method `value` shape is `Partial<Model>`.
```ts
export type MutationObject<DB, TB extends keyof DB> = {
    [C in keyof DB[TB]]?: MutationValueExpression<DB[TB][C]>;
};
```

So, Instead of passing single database model definition to `new Kysely<Models>`, it would be nice to allow user pass both selectable definition and insertable definition in the future. Then we could get stricter type for both insert and update mutation.

```ts
interface PersonSelectable {
  id: number
  created_at: string
  name: string
}

interface PersonInsertable {
  id?: number
  created_at?: string
  name: string
}

interface DatabaseSelectable {
  person: PersonSelectable
}

interface DatabaseInsertable {
  person: PersonInsertable
}

const db = new Kysely<DatabaseSelectable, DatabaseInsertable>

// it will throw error because name is required in PersonInsertable
await db.insertInto('person').values({})

```

Also, do you have any plan to build/integrate database typing generator into this library? I'm using patched version of `sql-ts` for now, it works great but it has some limitations. I could help on that if you like

Keep up the good work 👍

**Comment by koskimas** [comment]
That's an excellend idea and I considered it alot. The problem is values generated in the database, like `id` in this example (also all created_at and updated_at columns that are generated in the db).

If we required all required fields in the insert, in this example we'd also need to require the `id` which we definitely don't want to provide from the code.

The options:

## Separate interfaces for insert, update and select

This is your solution. This would cause the types to be at least twice as complex everywhere. We would need to pass around at least two `Database` interface everywhere. This adds too much complexity for a smallish impact.

## Decorators

Decorators are a runtime feature and since Kysely uses interfaces for which there is no runtime code, we cannot use decorators like this:

```ts
interface Person {
  @autogenerated
  id: number
}
```

##  Autogenerated specifier for inserts

In this option, the fields of the insert object are not optional. Instead, you need to either pass a value or a `db.generated` (or something similar) placeholder to tell Kysely to not insert the values.

```ts
await db.insertInto('person').values({
  id: db.generated,
 created_at: db.generated,
 name:  'Testerson',
})
```

Any thoughts on this option?

**Comment by tonivj5** [comment]
I really like the `db.generated` placeholder, looks explicit 👍🏻

**Comment by xiaoyu-tamu** [comment]
db.generated` is better and easier to implement :-)

`I should probably add some kind of realtime chat for Kysely. Slack maybe? Do you know any good free alternatives for open source projects? I've used gitter before, but it sucks`

I think either slack or discord will do the job

**Comment by tonivj5** [comment]
I think discord is more popular for OSS projects these days 😉

**Comment by koskimas** [comment]
All fields are now required for inserts in the latest 0.3.5 version and the `db.required` placeholder has been added. I wasn't able to make nullable fields optional, so any fields that has a type `T | null` and you want to leave to null, you need to explicitly set to null

```ts
await db.insertInto('person').values({
  id: db.generated,
  created_at: db.generated,
  name:  'Testerson',
  some_nullable_column: null,
})
````

**Comment by koskimas** [comment]
@xiaoyu-tamu  @tonivj5 There's now a discord badge in the readme. I don't know if I set it up correctly. Could you try it out?

**Comment by xiaoyu-tamu** [comment]
![image](https://user-images.githubusercontent.com/33362998/134356525-936bd82f-a989-4371-8884-b8d766cca798.png)

Looks like there is not channel available yet

**Comment by koskimas** [comment]
Weird. For me it opens a channel (there are a few). Maybe I need use the invite link in the badge? (I've never used discord). Here's the invite link https://discord.gg/C9aJ49mCra. Does that go to the right place?

**Comment by xiaoyu-tamu** [comment]
The invite link works.

**Comment by jirutka** [comment]
I have one idea how to solve this issue on the type level. I’ve developed it some time ago, but haven’t had time to integrate it into the project yet. I’ll dig it out once I have a while.

The main idea is to use generic wrapper types to encode metadata (such as PK), but in a way that doesn’t require any type casting when used, i.e. it behaves exactly like the wrapped type for the users. These wrappers are used in helper types that transform the model type into derived types (insertable, selectable etc.) and even allow things like “expanding” references.

It’s sorta black-magic-like typing, but it worked wonderfully. However, it need testing in real scenarios. I have a bit an unpleasant experience with TypeScript in the way that any complicated types fall apart in various corner cases, especially when you try to combine them with any other non-trivial types.

**Comment by koskimas** [comment]
@jirutka I'd love to see your solution!

**Comment by xiaoyu-tamu** [comment]
I created a typings and shortcuts generator that using kysely for kysely over this weekend.

This library is still work in progress and shortcut functions tests are missing. 

But the database introspection is ready to use.

https://github.com/xiaoyu-tamu/ormless/tree/main/example

```ts
import { CustomerRepository, Database, DatabaseSchema } from './database';

  const db = new Kysely<DatabaseSchema>({
    database: process.env.DATABASE_NAME!,
    host: process.env.DATABASE_HOST!,
    user: process.env.DATABASE_USER!,
    password: process.env.DATABASE_PASSWORD!,
    dialect: 'postgres',
    plugins: [new CamelCasePlugin()],
  });

const customerRepo = new CustomerRepository();
const select: Database.Customer.Column[] = ['active', 'activebool', 'lastName', 'firstName'];
// select unique customer by primary key
const fetchedCustomer = await customerRepo.selectOne({
db,
select,
where: { customerPkey: { customerId: -1 } },
});

// update unique customer by unique key
const updatedCustomer = await customerRepo.updateOne({
db,
select,
where: { customerEmailUk: { email: 'lookup@email.com' } },
data: { activebool: true },
});

```

**Comment by elderapo** [comment]
How about something like this:

```ts
import { table, t, Table, Selectable, Insertable, Updatable, Default } from "kysely";

export const Person = table({
  id: t.number("BIGINT").primary(), // table could ensure that table schema object contains exactly 1 primary column
  name: t.varchar(123).nullable(), // default length could be specified like this
  age: t.number("INT").default(18), // `number` is a little vague for a db so internal number type could be specifiable like this (in typesafe manner ofc)
});
export type Person = Table<typeof Person>; // this type would contain "metadata" (ex. `__generated__`, `__default__` ) that would be stripped out by below types

///

export type PersonSelectable = Selectable<Person>; // { id: readonly number; name: string | null; age: number; }
export type PersonInsertable = Insertable<Person>; // { name: string | null; age: number | Default }
export type PersonUpdatable = Updatable<Person>; // { name?: string | null; age?: number }
```

This is a long shot but a system like this would improve type-safety and would allow for automatic (at least semi-automatic) migrations generation `type-orm` style in the future.

**Comment by koskimas** [comment]
@elderapo Your suggestion is a different project completely. Kysely aims to be just a query builder. You build and execute queries. I don't see Kysely ever having that kind of model/automigration system.

**Comment by elderapo** [comment]
@koskimas I think you misunderstood what I meant :(

The part about auto migrations was solely a side effect (in fact cool/useful in my opinion but that's besides my point) of having a strongly defined schema. The main purpose of this strongly defined schema (ex. `id` a numeric value but auto-generated by the database) was to instruct `kysely` what it should expect from the user based on certain conditions ex.:
- when building an insert query `kysely` shouldn't expect the developer to specify `id` because its generation is going to be internally handled by the database engine but when some non-nullable/default column is omitted/skipped it should yell at compile time to not allow unnecessary runtime errors.
- when building an update query `kysely` shouldn't allow the developer to update of  `id` column of the user record because it's a primary key and it might mess up the relations of other records pointing to it (not 100% sure primary key updates are always bad and should be forbidden but it's just an example).


Essentially the `Selectable<T>`, `Insertable<T>`, `Updatable<T>` type helpers would be internally used by `kysely` to warn users at compile time about writing incorrect SQL queries :)

**Comment by koskimas** [comment]
Yes, the hard part is implementing the `Selectable`, `Insertable` etc. types. For them to work, we'd need to make the `Person` in your example a complex type with all kinds of metadata added into it. It wouldn't represent a `Person` row anymore. All types would need to use `Selectable<T>` etc. everywhere instead of just `T`.

For example, see the types in `table-parser.ts` file. Now consider the table types under the `DB` parameter were some kind of complex types where you'd need to use `Selectable<DB[T]>` to get the columns out.  I think the complexity would get out of hand.

Sure, the `Person` type in your example could simply be something like

```ts
{
  __insertable__: { foo: string }
 __selectable__: { foo: string, id: string }
}
```

and then `Selectable` would be

```ts
type Selectable<T extends { __selectable__: any }> = T['__selectable__']
```

that's easy. But using these internally wouldn't be.

**Comment by elderapo** [comment]
I totally agree that such a change would increase the complexity of the internal/library code but would also drastically improve the type-safety of the userland code which is the main purpose of this library, no?

I've quickly created a simple proof of concept of the `Selectable`, `Insertable`, `Updatable` types. You can check it out [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATgFQIYCMA20C8U1YQA8A3gLABQUUAlgCYBcUAwgPaYCuAtgHZE-d0SAHxQAZFAAKiGl1SIQAaQggA3JWoAzGojjAAcqi4QmbTryJ6ZPAObD1VKAgDGrHnUPHT7bnys1bUQl9DkxMDGwHalQbExYfCwEuIUQgqAAJVDgAEQhNVFDgBwBfe0pKVx49WiqkYHgkKDwACg4ERCYASVrEYAjiBpR+4QBKJgA3Vnom0RJih0rqjjA6VGAIQaaoZvomaVl5JRVkcAH2gmxhABooNqQmGBW1-qJBi4hRiam6Gag5hbc1Vi9XaWx2jCkMjkCmUIBOkFe52GYygAGUINhnH1CIikO9RAAfKACMK-EmYByUALtEFIZrkRzaXQGIxxABEyFYxgA1myrhonBBKh5WUxyTcAPQS4mhTBQViIJzAaw2WhweXcqAACyQ0CEzgKCFowAA5Oryf0BTE4uKoFKZaSFTLko0aOrWJqdYg9ULDdAaMBtVkoHQ8gVMIHxqhOBBKMURpSKMtVutBs0AIw3BlaHR6Tzs1CFvnlRz2gACwDgAFoIAAPSBYmuIRAKgUuNwirxQdMAJgAzPyKFbYkxM3GEyXk2sNu0M1mBUy86KoGzC6hi0PS9KK9W6w3gE2W4g20KO-nR-3B8ObbLB-HE+XKzX60KD0gj5Qp6nZ2z03y-veJaLIGcBcjOjR4MCaa9n2E6bjQmjbKBxiDCMfxtmBgwAHT0KodrSkkKQYSh7RYYuLLGHh9r+LYxHgYgWHtu4+ZUdKNGqkS5J0dh1qsc6KRQJxspxiWUpieJEmUBJ0liVAACyMQ0M4UBCJgrAAO5QAA8lhWlSTJ0midKyCotqGKQIqoCQHAlBWdAABKEBcKw4wQAAYi2XBaegABWr5EFpNzMKIeCSEp3IBVmUAANqKDUUDciorCIVpAC6TBabFqVQHW6zuOqzBQAA-MSECuYqTBxcU0WJSAyXaalZSbvaiggAgmAgDU6yIDw0ZmZgFk2ZudlQI5zmuQA4hAPBINOdBEMgOW1nldDqgAgjwcL9Lk2g8AGNBuCFo1OS57med5flYgtUUAPo3bEM2IHNd1MMqHDQKUDgjQpYAhGE-RwAtS0retm3vDtAT7YdWzZjFcUBAlSWIcg6X4FlwPTatfxQHdFqEC9UBvR9xXaVwAYLVlNxsnZbJpCQhOnEwyBZdF1OnGy2VCaSxRQEzWUlF9pzyagYA7eGlZA7lmOg1thAQ3twAHTwR2w7F8W1fVKN84o2VS-l2N3aG+SFATRNQDzJVaWTwAUzrVM03TDOQNrqWszTnMOnKPMuwLtlCwAostT1Yqizg6nI8IQHAHlcnJEB9CmqCS8t0tQBtsvYPLUPKzDcPq0j+Co8zOtu+z2XzCWI3p+DeSQ4rbhbI5riIPN7FRXZTAcDw3I8BpPDm01+n4DqRp9k4WqsKEPxCLcCDT513JtRinUBN1vVhCAldC90NIvItetY+8RCoJtwhHYHyqoCHYdOagkfR55ccJ88RACj9YuFIDY2nVNj1zUQP0-rhEIIDZmbI4A3zkBzM+whKBNRGo8ROOJ94p31kfE+IAz5bEkPIRW0ZX6OAvsHYAodw531OA-WO8dUCJwASLD+EYv4nUmtNWa6x5qANlADCm4DIHrkajAuBgtIBogxK+PeGM0EvAwVgvARCr4kL4ffGOXAn40Jfu-MMn86G-S4SAnhECyHQLPg+aUZhfBOyjlAKshMR7QDgBPKeKloB3HnrPJA6pgCsBDLXGaTg+FbxEWtDgXjf5sIgD8PA9M7oPXCXQU2iB3rm2EdAfY0IjidTwME0JrCnrsPEAbG6YAoSHFhAkpJFcKAjUyDkLREZc6GzqcAcpH0UlQCAf0BpN08bYBackv2IjzEWGQCrSxTN+nDSFmk0pxxTg3WTiDfA0jT4qwFGrBGGtkas0MbfDmRdtl8I5ujA+6pon3Vyc9G6r1EnExKmAnZUDXYlzZpADmvNSrlV9lUqZJSYSzIRCgxZ6CVnYN+RkyO8yRk1QLtMv5cI5kLWEKlRMI0j6AtTtXbavjs6jIeagJmeE7rYl6VcwmNzkn4SgGWZAWlshaSYP7KoHBvS2N1GqeUPAOrdikHFVw5h+4I1QE4AINhsCE0tBQIAA). Let me know what you think :)

**Comment by martinblostein** [comment]
> I totally agree that such a change would increase the complexity of the internal/library code but would also drastically improve the type-safety of the userland code which is the main purpose of this library, no?

I don't believe it would improve type safety at all beyond the current solution with `generated`. What am I missing?

It seems it would only make things a convenience a bit because you could use `insertInto` without specifying all columns.

**Comment by elderapo** [comment]
@martinblostein https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgaQJ4GcCmAbVAaOABQnRgHMpN0ARYAQ20wGN4BfOAMyghDgCIA1hhyo+AbgCwAKGnAAdjExQOdJpiJL0EOQH0AjImlw4wACYAuOHICuIAEZLJU4x2BRSOuXRCZLpKPJkTsbYdB5ePn4wAXJBRnBkmHKmSpZ8IAyYfHAAPvwcmBmM2Xl8EDAAFkri0qzSsgpKKmoa7to6AEyGziYWVrYOULn92NjBnG7h3r5w-oHjoVORs9Hz8YnJqfxFWcN8BTsl-OVVUDVSdTJS8orKqurUdDB0dmHqCPFgmu16loTfuj04y+bV0HT+AM6Tku0gA9LC4ABNCDWADkpjgTEoT3U2lxHDglSo6gA7lU5HBUCiVnRYJSUUM6GAwAA6aRMbSkOCmOxwAC8VkwJJQwlwAB5Hs9XlgAHwACg+PVM9EYLEsciFRBI5EoNBVzBgCtYAEo8LVjU5pGFUHImJxrLaYMBtNzChA5cbusY6CS6MB4DyWfIsLAAJIKd18EFaQF8Y0sgBuDGsVAV8WMZksegI8LgAAkIMLTBB6dYEph4JUnnBq1AHU6fCYCf7UehuU8Xm822BrFBIFhCSWNkocSYYAB+dMTdwwTzTNJ0Rd8M09EJhWcRGZ8Ow75dTjYpKBpQ4r4wmy09H1+gN2INyEMwcMwSPR9odOOJ5OpxXGDN9GyjDmCKVMAbagVYwAtHY1gwFOrgznOyx8IudB7qucCLBu878Dudhob+5abEe2yZPhcDnvUPQcve8CvhSApXv63J2FOLJYKqMAAGLcCAcqonRnSosarHsQacoANqovBSyYKiBB8GYfAALrCehLJkkomB8QJHRBqYclwKifIGXoqkESymAAB7MDBmAACp0AImCcZMhoWpRBHAAScp0Z6P4EXAdF6WIcC5jY9hKMMAHYHAZLAIwJgUti2D+sAY6tjW2C+hgNb9BFUBTpclxAA

**Comment by martinblostein** [comment]
> @martinblostein If you make:
> 
> * `id` nullable then when you select id from the db `kysely` types it as `number | null` which is inaccurate.
> * `id` optional then the same thing applies with the exception that type would essentially be `number | undefined` which is inaccurate as well.

I don't understand, if you type `id` as nullable, and then  `kysely` types it as `number | null` , why is that inaccurate?

If your issue is that you want `id` to be a generated column, make it non-nullable in the type and use `db.generated` as its value when inserted.

**Comment by elderapo** [comment]
`id` (primary keys) are usually not nullable on the schema (SQL level). However, you as a user don't need to specify them when inserting new records because they get automatically generated by the database engine.

**Comment by martinblostein** [comment]
I understand how generated columns work. What I'm saying is that there is a type-safe way of handling them in `kysely` currently. You mark the column as non-nullable in the type definition that represents the table, e.g.:

```
interface Person {
  id: number
  name: string
}

interface Database {
  people: Person
}
```

Then when you insert into that table, you use `db.generated` to avoid having to specify a value:

```
db.insertInto("people").values([{ id: db.generated, string: "Jim" }])
```

**Comment by elderapo** [comment]
@martinblostein please read my message again. I've misread your message initially and then edited it.

**Comment by martinblostein** [comment]
Ah, yes I see. You have a good point about how `db.generated` can be supplied to a non-generated column. That's not good. 

I'm hopefully that could be fixed by introducing using a `Generated<T>` type (as was suggested above.) Then db.generated could only be passed to those columns. The only remaining case is not allowing values to be passed to an `ALWAYS GENERATED`, which will throw an error if passed a value. I wonder if this could be achieved as well either via an `AlwaysGenerated<T>` type or another type parameter on `Generated`.

The reason I'm hopeful that a `Generated` generic type can solve this is that it wouldn't require many changes to the library. Your design is another good approach, but I agree with @koskimas that it's different enough that it probably deserves a separate project. Or at least a fork :)

**Comment by koskimas** [comment]
@elderapo We have to consider the tradeoff here. Your suggestion would achieve slightly better type safety since currently you can pass `db.generated` to a non-generated column. But on the other hand it would make all complex type magic in [table-parser.ts](https://github.com/koskimas/kysely/blob/master/src/parser/table-parser.ts) and [select-parser.ts](https://github.com/koskimas/kysely/blob/master/src/parser/select-parser.ts) (and many other places) much much more complex.

You can pass `db.raw` to anywhere anyway. If you really want, you can mess up all types using `db.raw`. So removing `db.generated` is not even that big of an improvement, and it's definitely not big enough to justify making all type magic impossible to read.

Currently the types, while complex, are still manageable. `DB` is always just a record of interfaces that represent the selected rows.

**Comment by koskimas** [comment]
I think this kind of general discussion should be continued in discord. I'll close this issue now.
