### ISSUE TITLE
AWS Data API

### ISSUE THREAD

**Issue by thdxr** [koskimas/kysely#9]
I work on [ServerlessStack](https://github.com/serverless-stack/serverless-stack) and I think this is the missing piece to make working with serverless relational databases a breeze. Let me explain a bit:

Prisma has gotten very popular and comes up a lot with our community. Typed query builders are definitely super helpful. However, their architecture involves shipping a rust binary that does the connection management and the node library talks directly to it.

This is a pretty crappy model for serverless since each function will be running that binary and you run into all kinds of connection pool issues. Prisma is launching their own proxy service that you can talk to over HTTP so the serverless functions don't have to run up the binary themselves. But this is another service to manage/pay for that adds latency.

AWS has a their own version of this called Data API built into their relational DB offering. Prisma will not integrate with this as it runs counter to their strategy and architecture. I'm planning on adding Data API support to this library which means we'll finally have a nice typed client for AWS RDS without worrying about connection management

Creating this issue so I can track my work

**Comment by koskimas** [comment]
I took a look at the AWS data API and It seems that we'll need to further abstract the `Driver` interface. At the moment, a new transaction is created by simply running a `BEGIN` SQL command on a normal connection. With the Data API a transaction is created using a separate method call.

I'll add the transaction creation to the `Driver` class's API so that drivers can implement it however they want.

**Comment by thdxr** [comment]
Ah that makes sense - no worries about breaking changes. I got a basic implementation working without transactions.

Some thoughts:
Right now DriverConfig is a fixed type that assumes all drivers need host, port, etc. For data api these variables aren't needed and it needs different variables. I worked around this by using the constructor to pass in additional params like this:

```
export class DataApiDialect implements Dialect {
  private readonly opts: DataApiDialectOpts

  constructor(opts: DataApiDialectOpts) {
    this.opts = opts
  }

  createDriver(config: DriverConfig): Driver {
    return new DataApiDriver(this.opts.driver, config)
  }

```

I was thinking maybe `Dialect` and `Driver` can take a generic (which can default to the current DriverConfig) to specify the type of the config?

Other than that, everything else seems great. I have to say, this is the best Typescript codebase I've ever seen. Sent it around to some people to learn from :smile:

**Comment by koskimas** [comment]
> Right now DriverConfig is a fixed type that assumes all drivers need host, port, etc ...

That's a good point. A lower level base class could indeed be a good idea. The config given to `Kysely.create` method also inherits the `DriverConfig` again making all the `host`, `port` etc. properties required.

I wonder if we could simply provide a `dialect` for the `Kysely.create`  like this:

```ts
const db = await Kysely.create({
  dialect: new DataApiDialect({
    // Postgres driver config here.
  })
})
```

and remove the whole `DriverConfig` interface. That way each dialect could have completely different config. The downside is slightly more complex initialization. What do you think?

> I'm also extending the DefaultQueryCompiler to tweak how bindings work and suggest that #bindings be made protected so I can override the appendValue implementation.

Would it be enought to add a  protected `addbinding` method that calls `#bindings.push`?

> Other than that, everything else seems great. I have to say, this is the best Typescript codebase I've ever seen. Sent it around to some people to learn from 😄

Thank you 😊  It really makes me happy to hear that 🍻

**Comment by koskimas** [comment]
The `Driver` interface now has theses methods

```ts
  async beginTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery({ sql: 'begin', bindings: [] })
  }

  async commitTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery({ sql: 'commit', bindings: [] })
  }

  async rollbackTransaction(connection: DatabaseConnection): Promise<void> {
    await connection.executeQuery({ sql: 'rollback', bindings: [] })
  }
```

You can override those to create a transaction using the Data API and save the transaction id to the connection object. The same connection is then used throughout the transaction.

> Should I be working on this as an external library or a PR to the main library?

Since this dialect won't be easily testable using Kysely's testbed, I think an external library would make more sense.

**Comment by thdxr** [comment]
Sweet I just got everything working minus transactions yesterday.  Updates to DefaultQueryCompiler look good too, will simplify a lot

**Comment by thdxr** [comment]
Running into some weird issue. I moved to a separate package and was making updates for the changes:

```
export class DataApiDriver extends Driver {
```

I get an error when trying to use it saying 
```
const connection = await this.#driver[driver_internal_js_1.INTERNAL_DRIVER_ACQUIRE_CONNECTION]();
                                                                                                      ^
TypeError: this[#driver][driver_internal_js_1.INTERNAL_DRIVER_ACQUIRE_CONNECTION] is not a function
```

It's strange because I'm inheriting from `Driver` so it should populate that function, not sure what's going on but I'll keep digging

**Comment by ClearedFram3** [comment]
> I plan to release Kysely with postgres, mysql and sqlite support. So far only postgres is supported. When I add other databases there's probably going to be some breaking changes.
Everyone seems to be going the support as many as possible route and I can see why. It seems to me that if you were to only support PG you would reduce overhead, workload, and would be deeply integrated giving this library its niche. This article really made me think of it: https://blog.js.wiki/news/2021/wiki-js-3-going-full-postgresql

**Comment by koskimas** [comment]
@ClearedFram3 The plan is to support the most common ones and provide a clear documented API for third parties to create more and maintain other dialects.

Supporting a handful of dialects out of the box isn't such a big deal since Kysely doesn't provide a "greatest common denominator API" like knex for example. With kysely, the generated queries are obvious from the code. For example when you write

```ts
db.insertInto('person').values(person).onConflictDoNothing('id')
```

on any dialect, even the ones that don't support the `ON CONFLICT` keyword, you still get the query

```ts
INSERT INTO "person" ("first_name", "last_name") VALUES ('Foo', 'Bar') ON CONFLICT ("id") DO NOTHING
```

On mysql you need to use the

```ts
db.insertInto('person').ignore().values(person)
```

which again ~directly translates in to SQL with a `INSERT IGNORE INTO "person"`.

This approach brings it's own challenges and third party dialects may not be able to implement all the features they want, but the code in `Kysely` remains simple.

Since I'm a big fan of postgres and  basically never use anything else if I have the choice, Kysely will probably heavily favor postgres features 😄

**Comment by koskimas** [comment]
@thdxr I opened a PR in kysely-data-api. https://github.com/serverless-stack/kysely-data-api/pull/2

**Comment by koskimas** [comment]
I think this can now be closed.
