### ISSUE TITLE
Packaging problem with electron

### ISSUE THREAD

**Issue by tibimunteanu** [koskimas/kysely#91]
I am using kysely with better-sqlite3 in electron.
It works when starting electron with `npm start` because I see that kysely lists all drivers for all dialects as dev dependencies, but when I package the electron app, it fails saying that it cannot find drivers for mysql and postgress.
![image](https://user-images.githubusercontent.com/1462924/166802378-cce76e63-785e-4d4c-8078-34290e3656d7.png)
I managed to have it working by commenting the requires for mysql and postgress in `node_modules/kysely/dist/cjs/index.js`.
![image](https://user-images.githubusercontent.com/1462924/166802584-2afc2a2a-98f0-4029-9ddd-06a9eb2639b1.png)

Is there a way to configure kysely not to require those?
Am I missing something?

**Comment by koskimas** [comment]
If you look at those files you commented out, they don't actually import the mysql or postgres drivers at the top of the file. The code imports them dynamically when you first use them. You don't need any drivers but the one you are using. I have no idea what you are doing to to get that error.

You can import stuff from `kysely/dist/esm/index-nodeless.js` or `kysely/dist/cjs/index-nodeless.js` instead of `kysely` to get a version that doesn't require node dependencies even dynamically.
